[project]
name = "WynntilsResolver"
version = "1.0.0"
description = "A simple resolver to analyze wynntils' encoded equipment in chat."
authors = [
    { name = "FYWinds", email = "i@windis.cn" },
]
dependencies = [
    "httpx==0.27.0",
]
requires-python = ">=3.8"
readme = "readme.md"
keywords = [
    "wynntils",
    "resolver",
    "wynncraft",
]
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.license]
text = "MIT"

[project.urls]
Homepage = "https://github.com/fywinds/WynntilsResolver"
Repository = "https://github.com/fywinds/WynntilsResolver"
Documentation = "https://github.com/fywinds/WynntilsResolver"
Changelog = "https://github.com/fywinds/WynntilsResolver"

[project.optional-dependencies]
dev = [
    "ruff==0.3.0",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.ruff]
line-length = 120
target-version = "py38"
exclude = [
    "temp/*",
]
src = [
    "src/wynntilsresolver",
]

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "UP",
    "C4",
    "T10",
    "T20",
    "PYI",
    "PT",
    "Q",
]
ignore = [
    "E402",
    "UP037",
]

[tool.black]
line-length = 120
target-version = [
    "py38",
    "py39",
    "py310",
    "py311",
    "py312",
]
