[project]
name = "WynntilsResolver"
version = "0.2.4"
description = "A simple resolver to analyze wynntils' encoded equipment in chat."
authors = [
    { name = "FYWinds", email = "i@windis.cn" },
]
dependencies = [
    "apscheduler==3.10.4",
]
requires-python = ">=3.8"
readme = "readme.md"
keywords = [
    "wynntils",
    "resolver",
    "wynncraft",
]
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.license]
text = "GLWTPL"

[project.urls]
Homepage = "https://github.com/fywinds/WynntilsResolver"
Repository = "https://github.com/fywinds/WynntilsResolver"
Documentation = "https://github.com/fywinds/WynntilsResolver"
Changelog = "https://github.com/fywinds/WynntilsResolver"

[project.optional-dependencies]
dev = [
    "ruff==0.1.8",
    "mypy==1.7.1",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm.build]
package-dir = "wynntilsresolver"

[tool.ruff]
line-length = 120
target-version = "py38"
src = [
    "wynntilsresolver",
]

[tool.black]
line-length = 120
target-version = [
    "py38",
    "py39",
    "py310",
    "py311",
    "py312",
]
